/*
    This file has been generated by bvtidl.pl. DO NOT MODIFY!
*/
#ifndef __BVTSONARDISCOVERYAGENT_H__
#define __BVTSONARDISCOVERYAGENT_H__

#include <bvt_c/bvt_retval.h>

#ifndef DOXY_IGNORE
#ifdef _WIN32
#	ifdef BUILDING_BVTSDK
#		define BVTSDK_EXPORT __declspec(dllexport)
#	else
#		define BVTSDK_EXPORT __declspec(dllimport)
#	endif
#else
#	if __GNUC__ >= 4
#		define BVTSDK_EXPORT __attribute__ ((visibility ("default")))
	#else
		#define BVTSDK_EXPORT
		#endif
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

/** \file
 * \defgroup BVTSonarDiscoveryAgent BVTSonarDiscoveryAgent Object
 * The SonarDiscoveryAgent is used to discover any BlueView
 * sonars resident on a network.
 * @{
*/

/** Opaque type for the BVTSonarDiscoveryAgent object */
typedef struct BVTOpaqueSonarDiscoveryAgent* BVTSonarDiscoveryAgent;

/** Create a BVTSonarDiscoveryAgent object */
BVTSDK_EXPORT BVTSonarDiscoveryAgent BVTSonarDiscoveryAgent_Create();
/** Destroy a BVTSonarDiscoveryAgent object
 * \param obj Object pointer
*/
BVTSDK_EXPORT void BVTSonarDiscoveryAgent_Destroy(BVTSonarDiscoveryAgent obj);

/** Causes the SonarDiscoveryAgent to begin probing the network for sonars.
 * \param obj Object pointer
 */
BVTSDK_EXPORT RetVal BVTSonarDiscoveryAgent_Start(BVTSonarDiscoveryAgent obj);

/** Number of sonars discovered.
 * \param obj Object pointer
 */
BVTSDK_EXPORT int BVTSonarDiscoveryAgent_GetSonarCount(BVTSonarDiscoveryAgent obj);

/** Returns the Host IP address (as a null-terminated string) for the specified sonar.
 * The SonarNum parameter is zero-based, that is, if GetSonarCount() returned a value of 3, then valid SonarNum values are 0, 1, and 2.
 * A buffer size of 20 characters should be sufficient for the HostBuffer.
 * \param obj Object pointer
 * \param SonarNum The sonar number to return 
 * \param HostBuffer buffer to hold the null-terminated string to be passed back 
 * \param HostBufferSize total number of characters the passed buffer can hold 
 */
BVTSDK_EXPORT RetVal BVTSonarDiscoveryAgent_GetSonarInfo(BVTSonarDiscoveryAgent obj, int SonarNum, char HostBuffer[], int HostBufferSize);

/** @}*/

#ifdef __cplusplus
}
#endif

#endif
